### ISSUE TITLE
branding

### ISSUE THREAD

**Issue by resatu** [resatu/boot#60]
name selection
email template selection
color palette
font palette
primary logo mark and word mark
secondary logo mark and/or word mark
partners logo mark and word mark
business card
blog post graphic template
webinar / vlog templates (open to suggestions)
event templates (open to suggestions)

**Comment by resatugurulu** [comment]
name selection
email template selection
color palette
font palette
primary logo mark and word mark
secondary logo mark and/or word mark
partners logo mark and word mark
business card
blog post graphic template
webinar / vlog templates (open to suggestions)
event templates (open to suggestions)
